### PR TITLE
Add support for inheritance

### PR DESCRIPTION
**Pull request by fred-sch**
I noticed that inheritance was just silently not supported. I thought it would be nice to add it. 

The current implementation should order the columns in the way they are added to the highest model in the hierarchy down to the lowest. Maybe this should be added to the Readme as well. 

I wonder what you think about it @patrick-zippenfenig ?

### CODE REVIEW

**Comment by patrick-zippenfenig** [comment]
Looks good to me. I never thought of that use case. However, the change from `static var` to `class var` is a breaking change. Do you see a way around that? Otherwise a major version bump would be ok.

**Comment by fred-sch** [comment]
I think it shouldn't be a breaking change. Actually I only adapted that in the test case, in the `ClickHouseModel` protocol it is still a `static var`. So it seems Swift is smart enough that a `class var` is still `static` and thus protocol conformance is given.

Also note that one could also specify an inherited class like this:

```swift
open class TestParentClass {
    @Field(key: "timestamp", isPrimary: true, isOrderBy: true)
    var timestamp: [Int64]

    @Field(key: "stationID", isPrimary: true, isOrderBy: true, isLowCardinality: true)
    var id: [String]
}

public final class InheritedTestModel: TestParentClass, ClickHouseModel {
    @Field(key: "temperature")
    var temperature: [Float]

    override public init() {}

    public static var engine: ClickHouseEngine {
        return ClickHouseEngineReplacingMergeTree(
            table: "testInherited",
            database: nil,
            cluster: nil,
            partitionBy: "toYYYYMM(toDateTime(timestamp))"
        )
    }
}
```
still using `static var`.

Would like me to adapt the unit test to rather have such an example?

**Comment by patrick-zippenfenig** [comment]
Oh, cool. I thought it would be a compile error. Could you update the readme with an additional example? This makes it easier for others to use

**Comment by fred-sch** [comment]
I added a short paragraph to the readme and adjusted the test to be a bit more self contained.

**Comment by patrick-zippenfenig** [comment]
Thanks!

**Pull request merged**
